### ISSUE TITLE
bugs of pour_out: objects flied away

### ISSUE THREAD

**Issue by rainbow979** [alters-mit/sticky_mitten_avatar#70] opened 2020-10-22 06:52 UTC

**Comment by rainbow979** [comment] 2020-10-22 12:55
[test1.txt](https://github.com/alters-mit/sticky_mitten_avatar/files/5422919/test1.txt)

**Comment by alters-mit** [comment] 2020-10-22 13:12
@rainbow979 Closing this ticket. This is not a bug. Sometimes, objects

**Closed** 2020-10-23 13:07 UTC
