### ISSUE TITLE
Container drop when moving_forward and turning without collision

### ISSUE THREAD

**Issue by rainbow979** [alters-mit/sticky_mitten_avatar#69] opened 2020-10-22 05:54 UTC

**Comment by jemsMIT** [comment] 2020-10-22 11:09
@rainbow979 Please provide more details. Do you mean the avatar let go of the container?

**Comment by rainbow979** [comment] 2020-10-22 12:26
branch: pour_out
First bug is in `move_forward_by` and `go_to`. I tested the avatar to grasp the container and move forward. But the avatar lost the container on the way. There was not collision.
Second bug is in 'turn_by'. When the avatar turned left, it seemed the arm didn't turn left with the avatar, which made the held container pour out

**Comment by rainbow979** [comment] 2020-10-22 12:29
[test.txt](https://github.com/alters-mit/sticky_mitten_avatar/files/5422760/test.txt)

**Comment by instbldrjems** [comment] 2020-10-22 12:44
@rainbow979 

> There was not collision.
In the video you submitted, the container does appear to collide with the object on the floor. This is not necessarily a bug.  The question is why it collides when you run the code, but did not when @alters-mit generated his video.  We will look at your posted code to see if there is any clue there.

**Comment by rainbow979** [comment] 2020-10-22 12:46
[test.txt](https://github.com/alters-mit/sticky_mitten_avatar/files/5422867/test.txt)

**Comment by alters-mit** [comment] 2020-10-22 13:51
Closing this issue.

> First bug is in move_forward_by and go_to. I tested the avatar to grasp the container and move forward. But the avatar lost the container on the way. There was not collision.

Not a bug. You lowered the height of the container with respect to the floor, causing the container to drag along the floor. The avatar can't always hold onto the container in these situations.

> Second bug is in 'turn_by'. When the avatar turned left, it seemed the arm didn't turn left with the avatar, which made the held container pour out

Not a bug. This behavior is OK.

**Closed by alters-mit** 2020-10-22 13:51 UTC
